language: python

group: travis_latest

git:
  depth: 25
  quiet: true

python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
  - "3.8-dev"  # 3.8 development branch
  - "nightly"  # nightly build

matrix:
  include:
    - python: 3.7           # this works for Linux but is ignored on macOS or Windows
      env: RUN_TESTS="true"
    - os: osx
      language: shell       # 'language: python' is an error on Travis CI macOS
      env: RUN_TESTS="true"

before_cache:
  - rm -f /home/travis/.cache/pip/log/debug.log

cache:
  directories:
  - /home/travis/miniconda3
  - /home/travis/.cache/pip

before_install:
  - source build_tools/travis/install.sh

install:
  - bash scripts/install_requirements.sh

script:
  - bash build_tools/travis/test_script.sh
